version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: appdb
  tests:
    build:
      context: ..
      dockerfile: ci/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./gradlew check -i'
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/appdb"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "qwerty"
    depends_on:
      - db