name: Test workflow

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Run tests
        run: docker-compose -f ci/docker-compose.yml run tests
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master